### ISSUE TITLE
How can we do "wait_for_msg_processed = false" in Send function? in version 1.9.3?

### ISSUE THREAD

**Issue by Zen-Somei** [shinolab/autd3-library-software#18]
@sssssssuzuki  I am currently using version 1.7.2. For creating LM by muyself, I set the second argument of the Send function "wait_for_msg_processed" to false. version 1.9.3 does not have the second argument of the Send function, and I did not know how to set  "wait_for_msg_processed "to false. Please give me your advice.

現在version 1.7.2を使っています。LMを自作するにあたり、Send関数の第2引数であるwait_for_msg_processedをfalseにしていました。version 1.9.3ではSend関数の第2引数が無くなっており、どのようにすればwait_for_msg_processedをfalseにできるのかわかりませんでした。アドバイスよろしくお願い致します。

**Comment by sssssssuzuki** [comment]
You should set `check_ack` flag false, but it is falsed by default, so there is no need to change it in v1.9 or later.

**Comment by Zen-Somei** [comment]
Thank you so much.
