### ISSUE TITLE
v1.7.2のlibraryの使用について

### ISSUE THREAD

**Issue by sSHIKU** [shinolab/autd3-library-software#20]
現在本郷のAUTDがv1.7.2用になっているとのことでv1.7.2のlibraryを使用してAUTDを使用しようとしています。

AUTD3 Developers Manual v1.10.0のSDKのバージョンをv1.10.0からv1.7.2に読み替えてそのままドキュメントに沿って(visual studioなどのバージョンは適宜読み替えて)動かすとエラーが出てしまいます。cmake .. -G "Visual Studio 16 2019" -A x64まではドキュメント通り行ってもエラーは出ておらず、build後に生成されたautd3_sample.slnをvisual studio 2019で開き"デバッグなしで開始"を選択するとエラーが出てしまいます。原因は何が考えられますか?

それぞれのバージョンは
visual studio 2019 16.9.5
npcap 1.31
cmake 3.21.3
です

よろしくお願いいたします。

**Comment by sssssssuzuki** [comment]
どういうコードでどういうエラーが出てるのかわからいないのでなんとも言えないですが, v1.7時代とv1.10は結構大きくAPIが変わってるので, そのままのコードは動かないです. example以下に当時のサンプルコードがあるのでそれを参考にしてください.

**Comment by sSHIKU** [comment]
ご対応いただきありがとうございます
