### ISSUE TITLE
ethernet cableについて

### ISSUE THREAD

**Issue by matsumurasoichiro** [shinolab/autd3-library-software#21]
プログラムを実行したあとにethernet cableの番号を選択すると思うのですが，windows updateによってethernet cableの番号が消えてしまします．windowsのバージョン回復以外にethernet cableを表示させる方法を御存知でしたら教えていただけないでしょうか？

**Comment by sssssssuzuki** [comment]
最新版のnpcapをインストールしても治らないですか?

**Comment by matsumurasoichiro** [comment]
治りました．ありがとうございました．
